### ISSUE TITLE
line number mismatch?

### ISSUE THREAD

**Issue by getify** [circlecell/jsonlintdotcom#18] opened 2014-10-16 18:55 UTC
I may be missing something obvious, but this appears to show a mismatch in line numbers between what's highlighted above and what's written in the error message below:

![screen shot 2014-10-16 at 9 50 47 am](https://cloud.githubusercontent.com/assets/150330/4668503/de406620-5565-11e4-917d-5df05306d971.png)

Any thoughts?

**Comment by antonyoneill** [comment] 2015-01-21 14:23
I'm seeing the same here, missing ',' on line 22 however error says line 25.
This isn't affected by the formatting as the line stays on 22!

**Comment by willberriss** [comment] 2015-01-22 08:54
Me too! The blue line highlighting feature is a few lines out. The pink results box line numbering is spot on and agrees with what I see in my text editor, vi.

**Comment by getify** [comment] 2015-01-22 15:10
FWIW, in my case, the blue line is correct, and error message reported in the ping box is wrong. Opposite of what @willberriss has reported.

**Comment by willberriss** [comment] 2015-01-23 14:28
Well, it's more bizarre than that. The blue highlighted line is the correct line of code, but the blue text says it's line 22. But in reality it's not at line 22 it's a line 25.  Both the pink box text and the editor vi say the line of code in question is at line 25. So they all agree on the line of code that has the error, but the blue box labels it line 22 but it should label it line 25.

**Comment by finom** [comment] 2015-10-30 14:28
@getify @antonyoneill @willberriss guys, can you provide an example of your JSON?

**Comment by getify** [comment] 2015-10-30 15:43
as this was over a year ago when first posted, I do not have any of that old context (the JSON I was using) anymore. sorry. :(

**Comment by BlockWorld** [comment] 2015-11-02 01:24
Strange. I took an example of JSON from `json.org/example.html` and it said `Valid JSON` (as expected) but when I changed the syntax on Line 20 which was `"GlossSee": "markup"` and I added a ~ to make it `"GlossSee: "markup"` and it gave me the correct error:
`Parse error on line 20:`
`..."GlossSee": "markup"~                }`
`-----------------------^`
`Expecting '}', ':', ',', ']'`

**Comment by finom** [comment] 2015-11-24 18:06
Cannot reproduce, closing.

**Closed by finom** 2015-11-24 18:06 UTC
